In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
%matplotlib inline
import seaborn as sns

In [12]:
train_raw = pd.read_csv("/Users/reetkanjilal/Hack/AVD_WNS/train_LZdllcl.csv")
test_raw = pd.read_csv("/Users/reetkanjilal/Hack/AVD_WNS/test_2umaH9m.csv")

In [3]:
train_raw.nunique()

employee_id             54808
department                  9
region                     34
education                   3
gender                      2
recruitment_channel         3
no_of_trainings            10
age                        41
previous_year_rating        5
length_of_service          35
KPIs_met >80%               2
awards_won?                 2
avg_training_score         61
is_promoted                 2
dtype: int64

In [4]:
test_raw.nunique()

employee_id             23490
department                  9
region                     34
education                   3
gender                      2
recruitment_channel         3
no_of_trainings             9
age                        41
previous_year_rating        5
length_of_service          34
KPIs_met >80%               2
awards_won?                 2
avg_training_score         61
dtype: int64

In [87]:
train_raw['length_of_service'].describe()

count    54808.000000
mean         5.865512
std          4.265094
min          1.000000
25%          3.000000
50%          5.000000
75%          7.000000
max         37.000000
Name: length_of_service, dtype: float64

Missing Value

In [5]:
# Function to calculate missing values by column# Funct 

def missing_value_table(df):
    mis_value = df.isnull().sum()
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_table = pd.concat([mis_value, mis_val_percent], axis = 1)
    mis_ren_clmn = mis_val_table.rename(columns = {0 : 'Missing Value', 1 : "percent missing"})
    mis_ren_clmn = mis_ren_clmn[mis_ren_clmn.iloc[:,1] !=0].sort_values('percent missing',ascending = False).round(1)
    return mis_ren_clmn

In [13]:
missing_value_table(train_raw)

                      Missing Value  percent missing
previous_year_rating           4124              7.5
education                      2409              4.4

Imputing missing value

In [20]:
train_raw.fillna(0,inplace=True)

In [21]:
test_raw.fillna(0,inplace=True)

In [22]:
missing_value_table(train_raw)

Empty DataFrame
Columns: [Missing Value, percent missing]
Index: []

In [33]:
train_raw['is_promoted'].value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [84]:
rating_ctab = pd.crosstab(index=train_raw['is_promoted'],columns=train_raw['previous_year_rating'],margins=1)

In [86]:
# rating_ctab
rating_ctab/rating_ctab.ix["All","All"]

/Users/reetkanjilal/ml/IIMB_kaggle/lib/python3.5/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

previous_year_rating,0.0,1.0,2.0,3.0,4.0,5.0,All
is_promoted,,,,,,,
0,0.069059,0.111936,0.073785,0.314972,0.165906,0.179171,0.91483
1,0.006185,0.001606,0.003302,0.024723,0.014304,0.035050,0.08517
All,0.075244,0.113542,0.077087,0.339695,0.180211,0.214221,1.00000

Dept feature

In [31]:
dept_ctab = pd.crosstab(index=train_raw['is_promoted'],columns=train_raw['department'],margins=1)

dept_ctab/dept_ctab.ix["All","All"]

/Users/reetkanjilal/ml/IIMB_kaggle/lib/python3.5/site-packages/ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

department,Analytics,Finance,HR,Legal,Operations,Procurement,R&D,Sales & Marketing,Technology,All
is_promoted,,,,,,,,,,
0,0.088308,0.042512,0.041636,0.017990,0.188385,0.117684,0.016968,0.285123,0.116224,0.91483
1,0.009342,0.003759,0.002481,0.000967,0.018665,0.012553,0.001259,0.022132,0.014013,0.08517
All,0.097650,0.046271,0.044118,0.018957,0.207050,0.130236,0.018227,0.307254,0.130236,1.00000

In [34]:
# length_of_service

train_raw[train_raw['previous_year_rating'].isnull()]['length_of_service'].describe()

count    4124.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: length_of_service, dtype: float64

In [35]:
train_raw.dtypes

employee_id               int64
department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [36]:
# one-hot encoding of categorical variables
train_d = pd.get_dummies(train_raw)
test_d = pd.get_dummies(test_raw)

print('Training Features shape: ', train_d.shape)
print('Testing Features shape: ', test_d.shape)

Training Features shape:  (54808, 61)
Testing Features shape:  (23490, 60)

In [66]:
train_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 59 columns):
no_of_trainings                 54808 non-null int64
age                             54808 non-null int64
previous_year_rating            54808 non-null float64
length_of_service               54808 non-null int64
KPIs_met >80%                   54808 non-null int64
awards_won?                     54808 non-null int64
avg_training_score              54808 non-null int64
department_Analytics            54808 non-null uint8
department_Finance              54808 non-null uint8
department_HR                   54808 non-null uint8
department_Legal                54808 non-null uint8
department_Operations           54808 non-null uint8
department_Procurement          54808 non-null uint8
department_R&D                  54808 non-null uint8
department_Sales & Marketing    54808 non-null uint8
department_Technology           54808 non-null uint8
region_region_1                 54808 non-null uint8
region_region_10                54808 non-null uint8
region_region_11                54808 non-null uint8
region_region_12                54808 non-null uint8
region_region_13                54808 non-null uint8
region_region_14                54808 non-null uint8
region_region_15                54808 non-null uint8
region_region_16                54808 non-null uint8
region_region_17                54808 non-null uint8
region_region_18                54808 non-null uint8
region_region_19                54808 non-null uint8
region_region_2                 54808 non-null uint8
region_region_20                54808 non-null uint8
region_region_21                54808 non-null uint8
region_region_22                54808 non-null uint8
region_region_23                54808 non-null uint8
region_region_24                54808 non-null uint8
region_region_25                54808 non-null uint8
region_region_26                54808 non-null uint8
region_region_27                54808 non-null uint8
region_region_28                54808 non-null uint8
region_region_29                54808 non-null uint8
region_region_3                 54808 non-null uint8
region_region_30                54808 non-null uint8
region_region_31                54808 non-null uint8
region_region_32                54808 non-null uint8
region_region_33                54808 non-null uint8
region_region_34                54808 non-null uint8
region_region_4                 54808 non-null uint8
region_region_5                 54808 non-null uint8
region_region_6                 54808 non-null uint8
region_region_7                 54808 non-null uint8
region_region_8                 54808 non-null uint8
region_region_9                 54808 non-null uint8
education_0                     54808 non-null uint8
education_Bachelor's            54808 non-null uint8
education_Below Secondary       54808 non-null uint8
education_Master's & above      54808 non-null uint8
gender_f                        54808 non-null uint8
gender_m                        54808 non-null uint8
recruitment_channel_other       54808 non-null uint8
recruitment_channel_referred    54808 non-null uint8
recruitment_channel_sourcing    54808 non-null uint8
dtypes: float64(1), int64(6), uint8(52)
memory usage: 5.6 MB

In [68]:
# train_labels = train_d['is_promoted']

# train_d = train_d.drop('employee_id',axis=1)
# test_d = test_d.drop('employee_id',axis=1)


train_d = train_d.drop('gender_f',axis=1)
test_d = test_d.drop('gender_f',axis=1)



# Align the training and testing data, keep only columns present in both dataframes
train_d, test_d = train_d.align(test_d, join = 'inner', axis = 1)

In [70]:
test_d.shape

(23490, 58)

In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

log_clf = LogisticRegression(random_state=42)
rnd_clf = RandomForestClassifier(random_state=42)
svm_clf = SVC(random_state=42)

voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='hard')

In [72]:
 voting_clf.fit(train_d, train_labels)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('rf', RandomFor...f',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [64]:
voting_clf.

<bound method VotingClassifier.get_params of VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('rf', RandomFor...f',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)>

In [73]:
test_pred = voting_clf.predict(test_d)

/Users/reetkanjilal/ml/IIMB_kaggle/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [75]:
# Submission dataframe
submit = test_raw[['employee_id']]
submit['is_promoted'] = test_pred

/Users/reetkanjilal/ml/IIMB_kaggle/lib/python3.5/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [76]:
submit['is_promoted'].value_counts()

# test_pred.to_csv('baseline.csv', index = False)

0    22969
1      521
Name: is_promoted, dtype: int64

In [77]:
submit.to_csv("baseline.csv")

EDA

AGE

In [92]:
pd.crosstab(index=train_raw['age'],columns=train_raw['is_promoted'],margins=1).to_csv('age_group.csv')

In [102]:
train_raw['age_group_1'] = np.where(np.logical_and(train_raw['age'] <= 31, train_raw['age'] >= 27),1,0)

test_raw['age_group_1'] = np.where(np.logical_and(test_raw['age'] <= 31, test_raw['age'] >= 27),1,0)

In [104]:
test_raw['age_group_1'].value_counts()

0    16317
1     7173
Name: age_group_1, dtype: int64

In [105]:
train_raw['age_group_2'] = np.where(np.logical_and(train_raw['age'] <= 35, train_raw['age'] >= 33),1,0)

test_raw['age_group_2'] = np.where(np.logical_and(test_raw['age'] <= 35, test_raw['age'] >= 33),1,0)

train_raw['age_group_2'].value_counts()

0    45811
1     8997
Name: age_group_2, dtype: int64

In [107]:
train_raw['age_group_3'] = np.where(np.logical_and(train_raw['age'] <= 39, train_raw['age'] >= 38),1,0)

test_raw['age_group_3'] = np.where(np.logical_and(test_raw['age'] <= 39, test_raw['age'] >= 38),1,0)

train_raw['age_group_3'].value_counts()

0    51190
1     3618
Name: age_group_3, dtype: int64

avg_training_score

In [111]:
pd.crosstab(index=train_raw['avg_training_score'],columns=train_raw['is_promoted'],margins=1).to_csv('avg_training_score.csv')

In [112]:
train_raw['avg_traiing_score_1'] = np.where(np.logical_and(train_raw['avg_training_score'] <= 87, train_raw['avg_training_score'] >= 80),1,0)

test_raw['avg_traiing_score_1'] = np.where(np.logical_and(test_raw['avg_training_score'] <= 87, test_raw['avg_training_score'] >= 80),1,0)

train_raw['avg_traiing_score_1'].value_counts()

0    45793
1     9015
Name: avg_traiing_score_1, dtype: int64

In [113]:
train_raw['avg_traiing_score_2'] = np.where(train_raw['avg_training_score'] == 88,1,0)

test_raw['avg_traiing_score_2'] = np.where(test_raw['avg_training_score'] == 88,1,0)

train_raw['avg_traiing_score_2'].value_counts()

0    54364
1      444
Name: avg_traiing_score_2, dtype: int64

In [114]:
train_raw['avg_traiing_score_3'] = np.where(train_raw['avg_training_score'] == 89,1,0)
test_raw['avg_traiing_score_3'] = np.where(test_raw['avg_training_score'] == 89,1,0)
train_raw['avg_traiing_score_3'].value_counts()

0    54507
1      301
Name: avg_traiing_score_3, dtype: int64

In [115]:
train_raw['avg_traiing_score_4'] = np.where(train_raw['avg_training_score'] == 90,1,0)
test_raw['avg_traiing_score_4'] = np.where(test_raw['avg_training_score'] == 90,1,0)
train_raw['avg_traiing_score_4'].value_counts()

0    54623
1      185
Name: avg_traiing_score_4, dtype: int64

In [116]:
train_raw['avg_traiing_score_5'] = np.where(train_raw['avg_training_score'] == 91,1,0)
test_raw['avg_traiing_score_5'] = np.where(test_raw['avg_training_score'] == 91,1,0)
train_raw['avg_traiing_score_5'].value_counts()

0    54691
1      117
Name: avg_traiing_score_5, dtype: int64

In [117]:
train_raw['avg_traiing_score_6'] = np.where(train_raw['avg_training_score'] == 92,1,0)
test_raw['avg_traiing_score_6'] = np.where(test_raw['avg_training_score'] == 92,1,0)
train_raw['avg_traiing_score_6'].value_counts()

0    54709
1       99
Name: avg_traiing_score_6, dtype: int64

In [118]:
train_raw['avg_traiing_score_7'] = np.where(train_raw['avg_training_score'] == 93,1,0)
test_raw['avg_traiing_score_7'] = np.where(test_raw['avg_training_score'] == 93,1,0)
train_raw['avg_traiing_score_7'].value_counts()

0    54724
1       84
Name: avg_traiing_score_7, dtype: int64

In [119]:
train_raw['avg_traiing_score_8'] = np.where(train_raw['avg_training_score'] >= 94,1,0)
test_raw['avg_traiing_score_8'] = np.where(test_raw['avg_training_score'] >= 94,1,0)
train_raw['avg_traiing_score_8'].value_counts()

0    54529
1      279
Name: avg_traiing_score_8, dtype: int64

length_of_service

In [120]:
pd.crosstab(index=train_raw['length_of_service'],columns=train_raw['is_promoted'],margins=1).to_csv('length_of_service.csv')

In [123]:
pd.crosstab(index=train_raw['KPIs_met >80%'],columns=train_raw['is_promoted'],margins=1)

is_promoted        0     1    All
KPIs_met >80%
0              34111  1406  35517
1              16029  3262  19291
All            50140  4668  54808

Data Prep for model 2

In [129]:
train_raw.nunique()

employee_id             54808
department                  9
region                     34
education                   4
gender                      2
recruitment_channel         3
no_of_trainings            10
age                        41
previous_year_rating        6
length_of_service          35
KPIs_met >80%               2
awards_won?                 2
avg_training_score         61
is_promoted                 2
age_group_1                 2
age_group_2                 2
age_group_3                 2
avg_traiing_score_1         2
avg_traiing_score_2         2
avg_traiing_score_3         2
avg_traiing_score_4         2
avg_traiing_score_5         2
avg_traiing_score_6         2
avg_traiing_score_7         2
avg_traiing_score_8         2
dtype: int64

In [182]:
to_convert = ['department','education','recruitment_channel']

In [142]:
dummy_train = pd.get_dummies(train_raw[to_convert])
dummy_test = pd.get_dummies(test_raw[to_convert])

model_df_train = pd.concat([train_raw.reset_index(drop=True),dummy_train],axis = 1)
model_df_test = pd.concat([test_raw.reset_index(drop=True),dummy_test],axis = 1)

# df_c = pd.concat([df_a.reset_index(drop=True), df_b], axis=1)

In [145]:
model_df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 41 columns):
employee_id                     54808 non-null int64
department                      54808 non-null object
region                          54808 non-null object
education                       54808 non-null object
gender                          54808 non-null object
recruitment_channel             54808 non-null object
no_of_trainings                 54808 non-null int64
age                             54808 non-null int64
previous_year_rating            54808 non-null float64
length_of_service               54808 non-null int64
KPIs_met >80%                   54808 non-null int64
awards_won?                     54808 non-null int64
avg_training_score              54808 non-null int64
is_promoted                     54808 non-null int64
age_group_1                     54808 non-null int64
age_group_2                     54808 non-null int64
age_group_3                     54808 non-null int64
avg_traiing_score_1             54808 non-null int64
avg_traiing_score_2             54808 non-null int64
avg_traiing_score_3             54808 non-null int64
avg_traiing_score_4             54808 non-null int64
avg_traiing_score_5             54808 non-null int64
avg_traiing_score_6             54808 non-null int64
avg_traiing_score_7             54808 non-null int64
avg_traiing_score_8             54808 non-null int64
department_Analytics            54808 non-null uint8
department_Finance              54808 non-null uint8
department_HR                   54808 non-null uint8
department_Legal                54808 non-null uint8
department_Operations           54808 non-null uint8
department_Procurement          54808 non-null uint8
department_R&D                  54808 non-null uint8
department_Sales & Marketing    54808 non-null uint8
department_Technology           54808 non-null uint8
education_0                     54808 non-null uint8
education_Bachelor's            54808 non-null uint8
education_Below Secondary       54808 non-null uint8
education_Master's & above      54808 non-null uint8
recruitment_channel_other       54808 non-null uint8
recruitment_channel_referred    54808 non-null uint8
recruitment_channel_sourcing    54808 non-null uint8
dtypes: float64(1), int64(19), object(5), uint8(16)
memory usage: 11.3+ MB

In [146]:
train_labels = model_df_train['is_promoted']
train_IDs = model_df_train['employee_id']
test_IDs = test_raw['employee_id']

In [150]:
# model_df_train['gender'].value_counts()
model_df_train['gender_m'] = np.where(model_df_train['gender'] == 'm',1,0)
model_df_test['gender_m'] = np.where(model_df_test['gender'] == 'm',1,0)

model_df_train['gender_m'].value_counts()

1    38496
0    16312
Name: gender_m, dtype: int64

In [156]:
# drop_column = ['employee_id','department','region','education','recruitment_channel','gender']

# model_df_train = model_df_train.drop(drop_column, axis=1)
# model_df_test = model_df_test.drop(drop_column, axis=1)

# Align the training and testing data, keep only columns present in both dataframes
model_df_train, model_df_test = model_df_train.align(model_df_test, join = 'inner', axis = 1)

In [157]:
log_clf = LogisticRegression(random_state=42)
rnd_clf = RandomForestClassifier(random_state=42)
svm_clf = SVC(random_state=42)

voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='hard')

In [158]:
voting_clf.fit(model_df_train, train_labels)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('rf', RandomFor...f',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [170]:
test_pred_df = pd.DataFrame(test_pred)

In [184]:
print ("pred len:",len(test_pred))

print ("id len:",len(test_raw))
test_IDs = test_raw['employee_id']

print ("id len:",len(test_IDs))

pred len: 23490
id len: 23490
id len: 23490

In [185]:
# test_pred = voting_clf.predict(model_df_test)
# Submission dataframe
submit = test_IDs
submit = pd.DataFrame(submit)
submit['is_promoted'] = test_pred

In [187]:
submit['is_promoted'].value_counts()

0    22921
1      569
Name: is_promoted, dtype: int64

In [188]:
submit.to_csv("baseline2.csv")

# Lets see H20 :)

In [189]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
import matplotlib.pylab as plt
import pandas as pd, numpy as np
from sklearn.metrics import mean_absolute_error
import xgboost as xgb
from hyperopt import hp, tpe, STATUS_OK, Trials, fmin
import h2o
from h2o.automl import H2OAutoML
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.grid.grid_search import H2OGridSearch
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: java version "1.8.0_112"; Java(TM) SE Runtime Environment (build 1.8.0_112-b16); Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
  Starting server from /Users/reetkanjilal/ml/IIMB_kaggle/lib/python3.5/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /var/folders/pg/3ws7rkfj09d1lc0slmsvt_tw0000gn/T/tmpx3omk3bl
  JVM stdout: /var/folders/pg/3ws7rkfj09d1lc0slmsvt_tw0000gn/T/tmpx3omk3bl/h2o_reetkanjilal_started_from_python.out
  JVM stderr: /var/folders/pg/3ws7rkfj09d1lc0slmsvt_tw0000gn/T/tmpx3omk3bl/h2o_reetkanjilal_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.

--------------------------  ----------------------------------------
H2O cluster uptime:         03 secs
H2O cluster timezone:       Asia/Kolkata
H2O data parsing timezone:  UTC
H2O cluster version:        3.20.0.7
H2O cluster version age:    14 days, 1 hour and 28 minutes
H2O cluster name:           H2O_from_python_reetkanjilal_nhmelh
H2O cluster total nodes:    1
H2O cluster free memory:    1.778 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             3.5.2 final
--------------------------  ----------------------------------------

In [212]:
train_raw = h2o.H2OFrame(train_raw)

employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,age_group_1,age_group_2,age_group_3,avg_traiing_score_1,avg_traiing_score_2,avg_traiing_score_3,avg_traiing_score_4,avg_traiing_score_5,avg_traiing_score_6,avg_traiing_score_7,avg_traiing_score_8
65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5,8,1,0,49,0,0,1,0,0,0,0,0,0,0,0,0
65141,Operations,region_22,Bachelor's,m,other,1,30,5,4,0,0,60,0,1,0,0,0,0,0,0,0,0,0,0
2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1,10,0,0,50,0,0,0,1,0,0,0,0,0,0,0,0
48945,Technology,region_26,Bachelor's,m,other,1,45,3,2,0,0,73,0,0,0,0,0,0,0,0,0,0,0,0
58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3,7,0,0,85,0,1,0,0,1,0,0,0,0,0,0,0
20379,Operations,region_20,Bachelor's,f,other,1,31,3,5,0,0,59,0,1,0,0,0,0,0,0,0,0,0,0
16290,Operations,region_34,Master's & above,m,sourcing,1,33,3,6,0,0,63,0,0,1,0,0,0,0,0,0,0,0,0
73202,Analytics,region_20,Bachelor's,m,other,1,28,4,5,0,0,83,0,1,0,0,1,0,0,0,0,0,0,0
29934,Technology,region_23,,m,sourcing,1,30,0,1,0,0,77,0,1,0,0,0,0,0,0,0,0,0,0
49017,Sales & Marketing,region_7,Bachelor's,f,sourcing,1,35,5,3,1,0,50,1,0,1,0,0,0,0,0,0,0,0,0

employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,age_group_1,age_group_2,age_group_3,avg_traiing_score_1,avg_traiing_score_2,avg_traiing_score_3,avg_traiing_score_4,avg_traiing_score_5,avg_traiing_score_6,avg_traiing_score_7,avg_traiing_score_8
65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5,8,1,0,49,0,0,1,0,0,0,0,0,0,0,0,0
65141,Operations,region_22,Bachelor's,m,other,1,30,5,4,0,0,60,0,1,0,0,0,0,0,0,0,0,0,0
2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1,10,0,0,50,0,0,0,1,0,0,0,0,0,0,0,0
48945,Technology,region_26,Bachelor's,m,other,1,45,3,2,0,0,73,0,0,0,0,0,0,0,0,0,0,0,0
58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3,7,0,0,85,0,1,0,0,1,0,0,0,0,0,0,0
20379,Operations,region_20,Bachelor's,f,other,1,31,3,5,0,0,59,0,1,0,0,0,0,0,0,0,0,0,0
16290,Operations,region_34,Master's & above,m,sourcing,1,33,3,6,0,0,63,0,0,1,0,0,0,0,0,0,0,0,0
73202,Analytics,region_20,Bachelor's,m,other,1,28,4,5,0,0,83,0,1,0,0,1,0,0,0,0,0,0,0
29934,Technology,region_23,,m,sourcing,1,30,0,1,0,0,77,0,1,0,0,0,0,0,0,0,0,0,0
49017,Sales & Marketing,region_7,Bachelor's,f,sourcing,1,35,5,3,1,0,50,1,0,1,0,0,0,0,0,0,0,0,0

H2OTypeError: Argument `python_obj` should be a None | list | tuple | dict | numpy.ndarray | pandas.DataFrame | scipy.sparse.issparse, got H2OFrame

employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,age_group_1,age_group_2,age_group_3,avg_traiing_score_1,avg_traiing_score_2,avg_traiing_score_3,avg_traiing_score_4,avg_traiing_score_5,avg_traiing_score_6,avg_traiing_score_7,avg_traiing_score_8
65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5,8,1,0,49,0,0,1,0,0,0,0,0,0,0,0,0
65141,Operations,region_22,Bachelor's,m,other,1,30,5,4,0,0,60,0,1,0,0,0,0,0,0,0,0,0,0
2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1,10,0,0,50,0,0,0,1,0,0,0,0,0,0,0,0
48945,Technology,region_26,Bachelor's,m,other,1,45,3,2,0,0,73,0,0,0,0,0,0,0,0,0,0,0,0
58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3,7,0,0,85,0,1,0,0,1,0,0,0,0,0,0,0
20379,Operations,region_20,Bachelor's,f,other,1,31,3,5,0,0,59,0,1,0,0,0,0,0,0,0,0,0,0
16290,Operations,region_34,Master's & above,m,sourcing,1,33,3,6,0,0,63,0,0,1,0,0,0,0,0,0,0,0,0
73202,Analytics,region_20,Bachelor's,m,other,1,28,4,5,0,0,83,0,1,0,0,1,0,0,0,0,0,0,0
29934,Technology,region_23,,m,sourcing,1,30,0,1,0,0,77,0,1,0,0,0,0,0,0,0,0,0,0
49017,Sales & Marketing,region_7,Bachelor's,f,sourcing,1,35,5,3,1,0,50,1,0,1,0,0,0,0,0,0,0,0,0

In [191]:
test_raw = h2o.H2OFrame(test_raw)

/Users/reetkanjilal/ml/IIMB_kaggle/lib/python3.5/site-packages/h2o/utils/shared_utils.py:177: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  data = _handle_python_lists(python_obj.as_matrix().tolist(), -1)[1]

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [203]:

y = 'is_promoted'
ID = 'employee_id'
train_raw.drop([ID], axis=1)
train, valid = train_raw.split_frame(ratios=[0.9], seed=1)


# For binary classification, response should be a factor
train[y] = train[y].asfactor()
valid[y] = valid[y].asfactor()

In [204]:
# Identify predictors and response
x = train.columns

aml = H2OAutoML(max_runtime_secs = 300)
aml.train(x = x, y = "is_promoted",
          training_frame = train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb

AutoML progress: |████████████████████████████████████████████████████████| 100%

model_id,auc,logloss,mean_per_class_error,rmse,mse
GBM_grid_0_AutoML_20180915_040553_model_0,0.909957,0.171129,0.315966,0.223968,0.0501618
StackedEnsemble_AllModels_0_AutoML_20180915_040553,0.909672,0.183145,0.312799,0.226773,0.0514261
StackedEnsemble_BestOfFamily_0_AutoML_20180915_040553,0.907751,0.184773,0.309483,0.227087,0.0515687
GBM_grid_0_AutoML_20180915_040553_model_2,0.9075,0.173424,0.317889,0.225398,0.0508042
GBM_grid_0_AutoML_20180915_040553_model_1,0.906694,0.173142,0.309251,0.225176,0.0507044
GBM_grid_0_AutoML_20180915_040553_model_5,0.906318,0.175052,0.311947,0.226005,0.051078
GBM_grid_0_AutoML_20180915_040553_model_4,0.906186,0.174858,0.3021,0.226319,0.0512201
GBM_grid_0_AutoML_20180915_040553_model_3,0.903709,0.178239,0.319063,0.228015,0.051991
GBM_grid_0_AutoML_20180915_040553_model_7,0.898375,0.205715,0.286366,0.24269,0.0588983
DRF_0_AutoML_20180915_040553,0.892982,0.190232,0.321139,0.233848,0.0546847

In [210]:
preds = aml.leader.predict(test_raw).as_data_frame()

gbm prediction progress: |████████████████████████████████████████████████| 100%

In [225]:
preds['employee_id'] = test_raw['employee_id'].as_data_frame()

In [226]:
preds.to_csv("autoMl_baseline.csv")

In [195]:
target = 'is_promoted'
ID = 'employee_id'
# train_raw.drop([ID], axis=1)
train, valid = train_raw.split_frame(ratios=[0.8], seed=1)
# valid = data.drop(train.index)
features = train.columns

In [196]:
cats = [feat for feat in features if 'cat' in feat]
for feat in cats:
    train[feat] = train[feat].asfactor()
    valid[feat] = valid[feat].asfactor()

y_train = (train[target])
y_valid = (valid[target])

In [197]:
# Identify predictors and response
x = train.columns

aml = H2OAutoML(max_runtime_secs = 30)
aml.train(x = x, y = "is_promoted",
          training_frame = train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb

AutoML progress: |████████████████████████████████████████████████████████| 100%

model_id,mean_residual_deviance,rmse,mse,mae,rmsle
StackedEnsemble_BestOfFamily_0_AutoML_20180915_034744,0.0539633,0.2323,0.0539633,0.11157,0.164099
StackedEnsemble_AllModels_0_AutoML_20180915_034744,0.0539633,0.2323,0.0539633,0.11157,0.164099
DRF_0_AutoML_20180915_034744,0.0544905,0.233432,0.0544905,0.107714,0.165778
XRT_0_AutoML_20180915_034744,0.0622095,0.249418,0.0622095,0.131204,0.180488

In [198]:
aml.leader

Model Details
=============
H2OStackedEnsembleEstimator :  Stacked Ensemble
Model Key:  StackedEnsemble_BestOfFamily_0_AutoML_20180915_034744
No model summary for this model


ModelMetricsRegressionGLM: stackedensemble
** Reported on train data. **

MSE: 0.0164080035783233
RMSE: 0.12809372966044552
MAE: 0.061262913537345025
RMSLE: 0.08494253263103484
R^2: 0.7965053462431467
Mean Residual Deviance: 0.0164080035783233
Null degrees of freedom: 28047
Residual degrees of freedom: 28045
Null deviance: 2261.5418924694754
Residual deviance: 460.21168436481196
AIC: -35672.11249486134

ModelMetricsRegressionGLM: stackedensemble
** Reported on validation data. **

MSE: 0.05005925020096957
RMSE: 0.22373924600071746
MAE: 0.10779843041384214
RMSLE: 0.15904617680267258
R^2: 0.3602453736987854
Mean Residual Deviance: 0.05005925020096957
Null degrees of freedom: 7116
Residual degrees of freedom: 7114
Null deviance: 556.9472814921231
Residual deviance: 356.2716836803004
AIC: -1107.0268286668818

ModelMetricsRegressionGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 0.05396325104714619
RMSE: 0.23229991615828488
MAE: 0.11156974876032866
RMSLE: 0.16409860482914837
R^2: 0.33073923131388583
Mean Residual Deviance: 0.05396325104714619
Null degrees of freedom: 28047
Residual degrees of freedom: 28045
Null deviance: 2261.7480636482846
Residual deviance: 1513.5612653703563
AIC: -2280.0137444095144

In [199]:
preds = aml.leader.predict(valid)

stackedensemble prediction progress: |████████████████████████████████████| 100%

In [200]:
preds

predict
-0.00490382
0.181385
0.056515
0.154886
0.0919312
0.101761
0.150127
-0.00490382
0.130886
0.136816


# GBM model

In [239]:
# GBM hyperparameters

gbm_params1 = {'learn_rate': [0.01, 0.1],
                'max_depth': [3, 5, 9],
                'sample_rate': [0.8, 1.0],
                'col_sample_rate': [0.2, 0.5, 1.0]}

# Train and validate a cartesian grid of GBMs
gbm_grid1 = H2OGridSearch(model=H2OGradientBoostingEstimator,
                          grid_id='gbm_grid1',
                          hyper_params=gbm_params1)
gbm_grid1.train(x=x, y="is_promoted",
                training_frame=train,
                validation_frame=valid,
                ntrees=500,
                seed=1)

gbm Grid Build progress: |████████████████████████████████████████████████| 100%

In [240]:
# Get the grid results, sorted by validation MAE
gbm_gridperf1 = gbm_grid1.get_grid()

In [259]:
gbm_gridperf1.models[0]

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  gbm_grid1_model_11


ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.04257601717257976
RMSE: 0.20633956763689254
LogLoss: 0.14544173978439964
Mean Per-Class Error: 0.1343520760592225
AUC: 0.9451128183929983
Gini: 0.8902256367859966
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.2613488177179304:

       0      1     Error    Rate
-----  -----  ----  -------  ----------------
0      35255  713   0.0198   (713.0/35968.0)
1      1547   1898  0.4491   (1547.0/3445.0)
Total  36802  2611  0.0573   (2260.0/39413.0)

Maximum Metrics: Maximum metrics at their respective thresholds

metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.261349     0.626816  168
max f2                       0.136685     0.680123  254
max f0point5                 0.417696     0.750667  115
max accuracy                 0.361179     0.94682   130
max precision                0.99784      1         0
max recall                   0.0099345    1         375
max specificity              0.99784      1         0
max absolute_mcc             0.295654     0.610156  153
max min_per_class_accuracy   0.135094     0.858986  255
max mean_per_class_accuracy  0.114113     0.865648  274

Gains/Lift Table: Avg response rate:  8.74 %, avg score:  8.73 %

    group    cumulative_data_fraction    lower_threshold    lift        cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  ----------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------
    1        0.0100221                   0.984365           11.4406     11.4406            1                0.993671    1                           0.993671            0.114659        0.114659                   1044.06   1044.06
    2        0.0200188                   0.937549           11.4406     11.4406            1                0.966483    1                           0.980094            0.114369        0.229028                   1044.06   1044.06
    3        0.0300155                   0.721236           11.2374     11.3729            0.982234         0.865029    0.994083                    0.941771            0.112337        0.341364                   1023.74   1037.29
    4        0.0400122                   0.379577           8.33366     10.6136            0.728426         0.494129    0.927711                    0.829932            0.0833091       0.424673                   733.366   961.36
    5        0.0500089                   0.307984           5.40091     9.57159            0.472081         0.33892     0.836631                    0.731779            0.0539913       0.478665                   440.091   857.159
    6        0.100018                    0.209856           3.5001      6.53585            0.305936         0.248528    0.571284                    0.490153            0.175036        0.653701                   250.01    553.585
    7        0.150001                    0.168762           2.23005     5.10107            0.194924         0.187705    0.445873                    0.389371            0.111466        0.765167                   123.005   410.107
    8        0.20001                     0.136836           1.79359     4.27409            0.156773         0.152316    0.373589                    0.3301              0.0896952       0.854862                   79.3586   327.409
    9        0.300003                    0.0884469          0.949274    3.16591            0.0829739        0.11205     0.276725                    0.257423            0.0949202       0.949782                   -5.0726   216.591
    10       0.399995                    0.0370722          0.383193    2.47028            0.033494         0.0632816   0.215921                    0.208891            0.0383164       0.988099                   -61.6807  147.028
    11       0.500013                    0.00963627         0.11609     1.99937            0.0101471        0.0205027   0.17476                     0.171207            0.011611        0.99971                    -88.391   99.9369
    12       0.600005                    0.00555664         0.00290298  1.66665            0.000253743      0.00705404  0.145678                    0.143851            0.000290276     1                          -99.7097  66.6653
    13       0.699997                    0.00369543         0           1.42858            0                0.0046012   0.124869                    0.123959            0               1                          -100      42.8577
    14       0.79999                     0.00197866         0           1.25002            0                0.00282264  0.109261                    0.108818            0               1                          -100      25.0016
    15       0.899982                    0.00132734         0           1.11113            0                0.00160463  0.0971216                   0.0969063           0               1                          -100      11.1133
    16       1                           0.000415789        0           1                  0                0.00103956  0.0874077                   0.0873179           0               1                          -100      0

ModelMetricsBinomial: gbm
** Reported on validation data. **

MSE: 0.04614216502817902
RMSE: 0.21480727415099105
LogLoss: 0.16206499497748447
Mean Per-Class Error: 0.1876358621443006
AUC: 0.9034320552733628
Gini: 0.8068641105467256
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.293980102459072:

       0     1    Error    Rate
-----  ----  ---  -------  --------------
0      4018  62   0.0152   (62.0/4080.0)
1      204   155  0.5682   (204.0/359.0)
Total  4222  217  0.0599   (266.0/4439.0)

Maximum Metrics: Maximum metrics at their respective thresholds

metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.29398      0.538194  112
max f2                       0.121496     0.576451  240
max f0point5                 0.671024     0.712575  55
max accuracy                 0.671024     0.945934  55
max precision                0.998969     1         0
max recall                   0.00712764   1         376
max specificity              0.998969     1         0
max absolute_mcc             0.671024     0.559519  55
max min_per_class_accuracy   0.110684     0.79902   251
max mean_per_class_accuracy  0.0467768    0.812364  320

Gains/Lift Table: Avg response rate:  8.09 %, avg score:  8.34 %

    group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  ---------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------
    1        0.0101374                   0.980945           12.3649    12.3649            1                0.993083    1                           0.993083            0.125348        0.125348                   1136.49   1136.49
    2        0.0200496                   0.897284           12.3649    12.3649            1                0.951894    1                           0.97272             0.122563        0.247911                   1136.49   1136.49
    3        0.030187                    0.459978           9.61715    11.4421            0.777778         0.725034    0.925373                    0.889542            0.097493        0.345404                   861.715   1044.21
    4        0.0400991                   0.333733           4.77735    9.79467            0.386364         0.371935    0.792135                    0.761594            0.0473538       0.392758                   377.735   879.467
    5        0.0500113                   0.290183           3.93429    8.63315            0.318182         0.309093    0.698198                    0.671909            0.0389972       0.431755                   293.429   763.315
    6        0.100023                    0.200451           2.11651    5.37483            0.171171         0.237831    0.434685                    0.45487             0.10585         0.537604                   111.651   437.483
    7        0.150034                    0.161593           2.28361    4.34443            0.184685         0.179986    0.351351                    0.363242            0.114206        0.651811                   128.361   334.443
    8        0.200045                    0.13302            1.55954    3.6482             0.126126         0.146718    0.295045                    0.309111            0.0779944       0.729805                   55.9537   264.82
    9        0.300068                    0.0889261          1.3089     2.86843            0.105856         0.111104    0.231982                    0.243109            0.130919        0.860724                   30.8897   186.843
    10       0.40009                     0.0390982          1.11396    2.42981            0.0900901        0.0648632   0.196509                    0.198547            0.111421        0.972145                   11.3955   142.981
    11       0.500113                    0.0101435          0.222791   1.98841            0.018018         0.0218935   0.160811                    0.163217            0.0222841       0.994429                   -77.7209  98.841
    12       0.59991                     0.00562322         0.0558235  1.66692            0.00451467       0.00723576  0.13481                     0.137269            0.00557103      1                          -94.4177  66.6917
    13       0.699932                    0.00371369         0          1.42871            0                0.00462782  0.115546                    0.118314            0               1                          -100      42.8709
    14       0.799955                    0.0020342          0          1.25007            0                0.0028535   0.101098                    0.103877            0               1                          -100      25.007
    15       0.899977                    0.00135888         0          1.11114            0                0.00163826  0.0898623                   0.0925145           0               1                          -100      11.1139
    16       1                           0.000425629        0          1                  0                0.00103531  0.0808741                   0.0833645           0               1                          -100      0

Scoring History:

     timestamp            duration    number_of_trees    training_rmse        training_logloss     training_auc        training_lift       training_classification_error    validation_rmse      validation_logloss    validation_auc      validation_lift     validation_classification_error
---  -------------------  ----------  -----------------  -------------------  -------------------  ------------------  ------------------  -------------------------------  -------------------  --------------------  ------------------  ------------------  ---------------------------------
     2018-09-15 17:11:22  47.386 sec  0.0                0.2824315858370088   0.2964988203564363   0.5                 1.0                 0.9125922918833888               0.27271989996431156  0.281172829587121     0.5                 1.0                 0.9191259292633476
     2018-09-15 17:11:22  47.441 sec  1.0                0.2746141472578808   0.2761373112716567   0.832196249109029   11.412597825777626  0.1341689290335676               0.2659662169390479   0.26406553678200806   0.8079636381014802  12.090126895697926  0.13268754223924306
     2018-09-15 17:11:22  47.478 sec  2.0                0.2685170746669173   0.26327465754382456  0.8499946170503437  11.412528929510062  0.12643036561540608              0.2606573454781385   0.253110814154708     0.8283153094106723  12.364902506963789  0.12164902004956071
     2018-09-15 17:11:22  47.515 sec  3.0                0.2645872670979961   0.25519181251062045  0.8546045646444639  11.412249925270197  0.1115114302387537               0.25732394467312564  0.24630305140981007   0.8316224261292261  12.364902506963789  0.10565442667267402
     2018-09-15 17:11:22  47.555 sec  4.0                0.26131565357117426  0.24872736805231122  0.8559164588810437  11.440638606676341  0.11036967498033644              0.2544995682696585   0.24071933810859433   0.8329465699928997  12.364902506963789  0.10678080648794773
---  ---                  ---         ---                ---                  ---                  ---                 ---                 ---                              ---                  ---                   ---                 ---                 ---
     2018-09-15 17:11:26  51.175 sec  66.0               0.21179397196705     0.1545050494830064   0.9363109209476316  11.440638606676341  0.06409052850582295              0.2158890525548371   0.1648072304599488    0.9013886613141079  12.364902506963789  0.06014868213561613
     2018-09-15 17:11:26  51.241 sec  67.0               0.21162440034278604  0.15422382272627555  0.9365294307728464  11.440638606676341  0.06259356050034252              0.21579763462599102  0.16464904162526714   0.9015170134906331  12.364902506963789  0.06059923406172561
     2018-09-15 17:11:26  51.301 sec  68.0               0.21141299840159947  0.1539240881852911   0.9367577219098802  11.440638606676341  0.06305026260370944              0.21565186238757256  0.16440360723488584   0.9017726937571686  12.364902506963789  0.05812119846812345
     2018-09-15 17:11:26  51.363 sec  69.0               0.21130541007518722  0.15373939913565815  0.9369606962357122  11.440638606676341  0.06266967751757034              0.21563207154118486  0.16435445481467625   0.901780203724944   12.364902506963789  0.05924757828339716
     2018-09-15 17:11:27  52.309 sec  100.0              0.20633956763689254  0.14544173978439964  0.9451128183929983  11.440638606676341  0.05734148631162307              0.21480727415099105  0.16206499497748447   0.9034320552733628  12.364902506963789  0.05992340617256139

See the whole table with table.as_data_frame()
Variable Importances:

variable             relative_importance    scaled_importance       percentage
-------------------  ---------------------  ----------------------  ----------------------
avg_training_score   2314.9853515625        1.0                     0.37886730008376035
department           1765.915283203125      0.7628192040227036      0.28900725228012486
KPIs_met >80%        696.2750244140625      0.30076865235631467     0.11395140726806806
region               439.9659118652344      0.19005127249219061     0.07200421248659929
awards_won?          277.74237060546875     0.11997586525461444     0.045454932144228806
---                  ---                    ---                     ---
avg_traiing_score_8  2.7584264278411865     0.0011915524329254982   0.0004514402531707194
avg_traiing_score_4  1.9887968301773071     0.0008590969393542677   0.0003254837379233734
avg_traiing_score_5  0.679533839225769      0.00029353699312486685  0.00011121156805992362
avg_traiing_score_6  0.0                    0.0                     0.0
avg_traiing_score_7  0.0                    0.0                     0.0

See the whole table with table.as_data_frame()

In [260]:
# Grab the top GBM model, chosen by validation MAE

# best_gbm_perf1 = best_gbm1.model_performance(valid)
# best_gbm_perf1

In [243]:
best_gbm1 = gbm_gridperf1.models[0]
preds = best_gbm1.predict(test_raw).as_data_frame()
preds['employee_id'] = test_raw['employee_id'].as_data_frame()
preds.to_csv("gbm_tune.csv")

gbm prediction progress: |████████████████████████████████████████████████| 100%

In [261]:
aml.leader

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_grid_0_AutoML_20180915_040553_model_0


ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.03872073906598925
RMSE: 0.19677585996760186
LogLoss: 0.13363674991318578
Mean Per-Class Error: 0.11190852370871429
AUC: 0.9616873148078707
Gini: 0.9233746296157415
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.27003551374618995:

       0      1     Error    Rate
-----  -----  ----  -------  ----------------
0      28238  428   0.0149   (428.0/28666.0)
1      1070   1706  0.3854   (1070.0/2776.0)
Total  29308  2134  0.0476   (1498.0/31442.0)

Maximum Metrics: Maximum metrics at their respective thresholds

metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.270036     0.694908  175
max f2                       0.167044     0.73225   239
max f0point5                 0.396511     0.798185  130
max accuracy                 0.300844     0.953756  161
max precision                0.996895     1         0
max recall                   0.00912787   1         379
max specificity              0.996895     1         0
max absolute_mcc             0.280576     0.677748  170
max min_per_class_accuracy   0.147863     0.885055  253
max mean_per_class_accuracy  0.135145     0.888091  263

Gains/Lift Table: Avg response rate:  8.83 %, avg score:  8.85 %

    group    cumulative_data_fraction    lower_threshold    lift        cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  ----------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------
    1        0.0100184                   0.98409            11.3264     11.3264            1                0.991876    1                           0.991876            0.113473        0.113473                   1032.64   1032.64
    2        0.0200051                   0.926143           11.3264     11.3264            1                0.960793    1                           0.976359            0.113112        0.226585                   1032.64   1032.64
    3        0.0300235                   0.752376           11.2904     11.3144            0.996825         0.863247    0.998941                    0.938615            0.113112        0.339697                   1029.04   1031.44
    4        0.0400102                   0.438627           10.3885     11.0833            0.917197         0.578893    0.978537                    0.848828            0.103746        0.443444                   938.852   1008.33
    5        0.0500286                   0.336757           7.33517     10.3327            0.647619         0.378726    0.91227                     0.754688            0.073487        0.516931                   633.517   933.27
    6        0.100025                    0.217359           4.21497     7.27481            0.372137         0.260923    0.642289                    0.507884            0.210735        0.727666                   321.497   627.481
    7        0.150022                    0.168975           2.11829     5.55633            0.187023         0.191717    0.490566                    0.402517            0.105908        0.833573                   111.829   455.633
    8        0.200019                    0.136937           1.46263     4.53307            0.129135         0.152364    0.400223                    0.339989            0.0731268       0.9067                     46.2629   353.307
    9        0.300013                    0.0840512          0.626841    3.23113            0.0553435        0.109435    0.285275                    0.263146            0.0626801       0.96938                    -37.3159  223.113
    10       0.400006                    0.0344873          0.234165    2.48195            0.0206743        0.060052    0.21913                     0.212376            0.023415        0.992795                   -76.5835  148.195
    11       0.5                         0.0101312          0.0648456   1.99856            0.00572519       0.0190091   0.176452                    0.173705            0.00648415      0.99928                    -93.5154  99.8559
    12       0.599994                    0.00522183         0.00720507  1.66668            0.000636132      0.00707717  0.147151                    0.145935            0.000720461     1                          -99.2795  66.6684
    13       0.699987                    0.00341168         0           1.4286             0                0.0042581   0.12613                     0.125697            0               1                          -100      42.8597
    14       0.799981                    0.00213298         0           1.25003            0                0.00271047  0.110365                    0.110324            0               1                          -100      25.003
    15       0.899975                    0.00141964         0           1.11114            0                0.00174829  0.0981023                   0.0982605           0               1                          -100      11.1143
    16       1                           0.000490023        0           1                  0                0.0011193   0.0882895                   0.0885439           0               1                          -100      0

ModelMetricsBinomial: gbm
** Reported on validation data. **

MSE: 0.048547825379993935
RMSE: 0.22033571063264787
LogLoss: 0.16728138074633989
Mean Per-Class Error: 0.17901508647425057
AUC: 0.9061101469425622
Gini: 0.8122202938851244
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.31783317519355336:

       0     1    Error    Rate
-----  ----  ---  -------  --------------
0      7187  115  0.0157   (115.0/7302.0)
1      397   272  0.5934   (397.0/669.0)
Total  7584  387  0.0642   (512.0/7971.0)

Maximum Metrics: Maximum metrics at their respective thresholds

metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.317833     0.515152  129
max f2                       0.104047     0.590402  274
max f0point5                 0.536536     0.698023  78
max accuracy                 0.536536     0.943169  78
max precision                0.998245     1         0
max recall                   0.00305117   1         390
max specificity              0.998245     1         0
max absolute_mcc             0.531066     0.550391  79
max min_per_class_accuracy   0.111587     0.807313  266
max mean_per_class_accuracy  0.0654128    0.820985  312

Gains/Lift Table: Avg response rate:  8.39 %, avg score:  8.58 %

    group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  ---------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------
    1        0.0100364                   0.981572           11.9148    11.9148            1                0.990795    1                           0.990795            0.119581        0.119581                   1091.48   1091.48
    2        0.0200728                   0.892178           11.3191    11.6169            0.95             0.948362    0.975                       0.969579            0.113602        0.233184                   1031.91   1061.69
    3        0.0301091                   0.575379           10.5744    11.2694            0.8875           0.777492    0.945833                    0.90555             0.106129        0.339312                   957.438   1026.94
    4        0.0400201                   0.36471            4.07215    9.48702            0.341772         0.443361    0.796238                    0.791089            0.0403587       0.379671                   307.215   848.702
    5        0.0500565                   0.310071           3.12763    8.21195            0.2625           0.333626    0.689223                    0.699367            0.0313901       0.411061                   212.763   721.195
    6        0.100113                    0.214472           2.41879    5.31537            0.203008         0.250428    0.446115                    0.474898            0.121076        0.532138                   141.879   431.537
    7        0.150044                    0.170438           2.15544    4.26382            0.180905         0.190482    0.35786                     0.380251            0.107623        0.639761                   115.544   326.382
    8        0.2001                      0.135789           1.61253    3.60058            0.135338         0.151839    0.302194                    0.323112            0.0807175       0.720478                   61.2529   260.058
    9        0.300088                    0.0871173          1.58465    2.92889            0.132999         0.109399    0.245819                    0.251904            0.158445        0.878924                   58.4653   192.889
    10       0.400075                    0.0399181          0.867074   2.4136             0.0727729        0.0635377   0.202571                    0.204827            0.0866966       0.96562                    -13.2926  141.36
    11       0.500063                    0.0104145          0.313941   1.99377            0.0263488        0.0211604   0.167336                    0.168103            0.0313901       0.99701                    -68.6059  99.3771
    12       0.60005                     0.0052724          0.0149496  1.66404            0.00125471       0.00725539  0.139661                    0.141301            0.00149477      0.998505                   -98.505   66.4036
    13       0.700038                    0.0033348          0          1.42636            0                0.00419191  0.119713                    0.121717            0               0.998505                   -100      42.6359
    14       0.800025                    0.00213134         0.0149496  1.24996            0.00125471       0.00269117  0.104908                    0.106841            0.00149477      1                          -98.505   24.9961
    15       0.900013                    0.00143481         0          1.1111             0                0.00175501  0.0932534                   0.0951667           0               1                          -100      11.1096
    16       1                           0.000507516        0          1                  0                0.00112465  0.0839292                   0.0857637           0               1                          -100      0

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.05016175589397314
RMSE: 0.22396820286365013
LogLoss: 0.1711294624244225
Mean Per-Class Error: 0.17776869836058784
AUC: 0.9099568208408841
Gini: 0.8199136416817683
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.39301065186210926:

       0      1     Error    Rate
-----  -----  ----  -------  ----------------
0      28426  240   0.0084   (240.0/28666.0)
1      1731   1045  0.6236   (1731.0/2776.0)
Total  30157  1285  0.0627   (1971.0/31442.0)

Maximum Metrics: Maximum metrics at their respective thresholds

metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.393011     0.514652  126
max f2                       0.0961218    0.603514  293
max f0point5                 0.549234     0.689959  94
max accuracy                 0.549234     0.939412  94
max precision                0.997139     1         0
max recall                   0.00345741   1         391
max specificity              0.997139     1         0
max absolute_mcc             0.549234     0.541235  94
max min_per_class_accuracy   0.111823     0.811135  279
max mean_per_class_accuracy  0.0759186    0.822231  310

Gains/Lift Table: Avg response rate:  8.83 %, avg score:  8.64 %

    group    cumulative_data_fraction    lower_threshold    lift        cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  ----------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------
    1        0.0100184                   0.980612           11.3264     11.3264            1                0.990856    1                           0.990856            0.113473        0.113473                   1032.64   1032.64
    2        0.0200051                   0.900771           11.2182     11.2723            0.990446         0.948146    0.995231                    0.969535            0.112032        0.225504                   1021.82   1027.23
    3        0.0300235                   0.629568           9.96001     10.8344            0.879365         0.800157    0.956568                    0.913016            0.0997839       0.325288                   896.001   983.444
    4        0.0400102                   0.399188           4.65319     9.29158            0.410828         0.483094    0.82035                     0.805706            0.0464697       0.371758                   365.319   829.158
    5        0.0500286                   0.324456           2.80462     7.99254            0.247619         0.358791    0.705658                    0.716209            0.028098        0.399856                   180.462   699.254
    6        0.100025                    0.214783           2.75954     5.37687            0.243639         0.256209    0.474722                    0.486282            0.137968        0.537824                   175.954   437.687
    7        0.150022                    0.169994           2.16873     4.30772            0.191476         0.190712    0.380326                    0.38778             0.108429        0.646254                   116.873   330.772
    8        0.200019                    0.136668           1.90214     3.70642            0.167939         0.153405    0.327238                    0.329195            0.0951009       0.741354                   90.2138   270.642
    9        0.300013                    0.0835884          1.43741     2.95016            0.126908         0.108758    0.260469                    0.255724            0.143732        0.885086                   43.7411   195.016
    10       0.400006                    0.0345823          0.835788    2.42161            0.0737913        0.0594154   0.213803                    0.206651            0.0835735       0.96866                    -16.4212  142.161
    11       0.5                         0.0103436          0.277395    1.9928             0.0244911        0.019385    0.175943                    0.1692              0.0277378       0.996398                   -72.2605  99.2795
    12       0.599994                    0.00543075         0.0216152   1.66428            0.0019084        0.00735342  0.146939                    0.142227            0.00216138      0.998559                   -97.8385  66.4283
    13       0.699987                    0.00358328         0.0108076   1.42808            0.000954198      0.00442281  0.126085                    0.122542            0.00108069      0.99964                    -98.9192  42.8083
    14       0.799981                    0.00231725         0.00360253  1.25003            0.000318066      0.00291096  0.110365                    0.107588            0.000360231     1                          -99.6397  25.003
    15       0.899975                    0.00154232         0           1.11114            0                0.00190125  0.0981023                   0.0958457           0               1                          -100      11.1143
    16       1                           0.000357025        0           1                  0                0.00117397  0.0882895                   0.0863761           0               1                          -100      0

Cross-Validation Metrics Summary:

                         mean       sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ---------  ----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.9272     0.0110534   0.914295      0.903005      0.93909       0.942112      0.9375
auc                      0.909815   0.00519202  0.920145      0.899421      0.913626      0.912021      0.903863
err                      0.0727995  0.0110534   0.0857052     0.0969948     0.0609097     0.057888      0.0625
err_count                457.8      69.5347     539           610           383           364           393
f0point5                 0.603568   0.0556671   0.55414       0.473211      0.670233      0.678972      0.641283
f1                       0.521388   0.0187582   0.563563      0.491667      0.526576      0.530928      0.494208
f2                       0.471292   0.0441657   0.573311      0.51162       0.433632      0.435887      0.40201
lift_top_group           11.3483    0.346608    10.4817       11.2103       11.4536       11.8866       11.7095
logloss                  0.171129   0.00403052  0.172769      0.180367      0.167259      0.163448      0.171803
max_per_class_error      0.551844   0.0622106   0.42          0.474153      0.612022      0.610586      0.642458
mcc                      0.509974   0.0267307   0.516342      0.43944       0.538484      0.546257      0.50935
mean_per_class_accuracy  0.710662   0.0235274   0.764776      0.732895      0.689894      0.691147      0.674598
mean_per_class_error     0.289338   0.0235274   0.235224      0.267105      0.310106      0.308853      0.325402
mse                      0.0501616  0.00125917  0.0510216     0.0528713     0.0491965     0.047546      0.0501727
precision                0.692586   0.110363    0.548032      0.461659      0.819231      0.834008      0.8
r2                       0.376249   0.0149012   0.408805      0.349245      0.382622      0.382927      0.357645
recall                   0.448156   0.0622106   0.58          0.525847      0.387978      0.389414      0.357542
rmse                     0.223933   0.00281052  0.22588       0.229938      0.221803      0.21805       0.223993
specificity              0.973168   0.0165511   0.949552      0.939944      0.99181       0.992881      0.991654

Scoring History:

    timestamp            duration    number_of_trees    training_rmse    training_logloss    training_auc    training_lift    training_classification_error    validation_rmse    validation_logloss    validation_auc    validation_lift    validation_classification_error
--  -------------------  ----------  -----------------  ---------------  ------------------  --------------  ---------------  -------------------------------  -----------------  --------------------  ----------------  -----------------  ---------------------------------
    2018-09-15 04:07:22  18.552 sec  0                  0.283716         0.298562            0.5             1                0.91171                          0.277316           0.288382              0.5               1                  0.916071
    2018-09-15 04:07:22  18.732 sec  5                  0.259522         0.243866            0.886295        11.3264          0.0818968                        0.25644            0.241552              0.85932           11.0212            0.10074
    2018-09-15 04:07:22  18.874 sec  10                 0.241157         0.211201            0.91274         11.3264          0.0807519                        0.241443           0.21349               0.889459          11.3191            0.0918329
    2018-09-15 04:07:22  19.009 sec  15                 0.231604         0.193131            0.919356        11.3264          0.066567                         0.234383           0.198603              0.894764          11.468             0.0649856
    2018-09-15 04:07:22  19.144 sec  20                 0.224635         0.180343            0.925866        11.3264          0.0677756                        0.229367           0.188351              0.900257          11.468             0.076402
    2018-09-15 04:07:23  19.281 sec  25                 0.220093         0.171168            0.929553        11.3264          0.0621144                        0.226395           0.181527              0.901545          11.468             0.0780329
    2018-09-15 04:07:23  19.417 sec  30                 0.217312         0.165597            0.932439        11.3264          0.0596018                        0.224919           0.177758              0.902496          11.6169            0.0792874
    2018-09-15 04:07:23  19.551 sec  35                 0.214891         0.161606            0.936113        11.3264          0.0589339                        0.223733           0.175456              0.903877          11.6169            0.0626019
    2018-09-15 04:07:23  19.688 sec  40                 0.212542         0.157714            0.939265        11.3264          0.0589975                        0.22257            0.173236              0.905084          11.9148            0.0618492
    2018-09-15 04:07:23  19.826 sec  45                 0.210452         0.154027            0.942668        11.3264          0.0582024                        0.222022           0.17179               0.905653          11.9148            0.0642328
    2018-09-15 04:07:23  19.962 sec  50                 0.208333         0.150846            0.945924        11.3264          0.0582024                        0.221738           0.171066              0.906061          11.9148            0.0642328
    2018-09-15 04:07:23  20.104 sec  55                 0.205921         0.14708             0.949631        11.3264          0.055181                         0.22129            0.169934              0.905839          11.9148            0.0668674
    2018-09-15 04:07:23  20.250 sec  60                 0.204188         0.144498            0.952212        11.3264          0.0526684                        0.221016           0.16913               0.906451          11.9148            0.0592147
    2018-09-15 04:07:24  20.393 sec  65                 0.20282          0.142437            0.953703        11.3264          0.052573                         0.220652           0.168397              0.906589          11.9148            0.065111
    2018-09-15 04:07:24  20.542 sec  70                 0.201142         0.139802            0.955813        11.3264          0.0521913                        0.220355           0.16774               0.906544          11.9148            0.0643583
    2018-09-15 04:07:24  20.683 sec  75                 0.199489         0.137394            0.957934        11.3264          0.0497424                        0.220324           0.167492              0.90603           11.9148            0.0647347
    2018-09-15 04:07:24  20.821 sec  80                 0.198088         0.135442            0.960028        11.3264          0.04882                          0.220242           0.16723               0.906323          11.9148            0.0648601
    2018-09-15 04:07:24  20.958 sec  85                 0.196776         0.133637            0.961687        11.3264          0.0476433                        0.220336           0.167281              0.90611           11.9148            0.0642328

Variable Importances:

variable             relative_importance    scaled_importance     percentage
-------------------  ---------------------  --------------------  ---------------------
avg_training_score   1508.3416748046875     1.0                   0.2771180478872574
department           1324.8106689453125     0.8783226579726108    0.24339906039251716
KPIs_met >80%        591.5279541015625      0.39217106043175426   0.10867767870472338
region               532.3702392578125      0.3529506929036806    0.09780900701792283
avg_traiing_score_8  265.049072265625       0.17572217004475843   0.04869578473331615
---                  ---                    ---                   ---
avg_traiing_score_3  15.09078598022461      0.010004885651772957  0.0027725343811545525
age_group_2          13.587329864501953     0.009008124678555576  0.002496313926046349
age_group_1          12.525506973266602     0.00830415759406005   0.0023012319418140655
age_group_3          10.180352210998535     0.006749367455034199  0.0018703715336128638
avg_traiing_score_2  8.3097505569458        0.005509196421309393  0.0015266977577007234

See the whole table with table.as_data_frame()

In [236]:
preds_aml = aml.leader.predict(test_raw).as_data_frame()
preds_aml['employee_id'] = test_raw['employee_id'].as_data_frame()
preds_aml.to_csv("aml_baseline1.csv")

gbm prediction progress: |████████████████████████████████████████████████| 100%

In [238]:
submit.head()

   employee_id  is_promoted
0         8724            0
1        74430            0
2        72255            0
3        38562            0
4        64486            0

# stacked ensable

In [250]:
import h2o
from h2o.estimators.random_forest import H2ORandomForestEstimator
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.estimators.stackedensemble import H2OStackedEnsembleEstimator
from h2o.grid.grid_search import H2OGridSearch
from __future__ import print_function

In [251]:
x = train_raw.columns
y = "is_promoted"
x.remove(y)

ID = 'employee_id'
x.remove(ID)

train_raw[y] = train_raw[y].asfactor()

In [252]:
ID = 'employee_id'
x.remove(ID)

train_raw[y] = train_raw[y].asfactor()

In [265]:
# Number of CV folds (to generate level-one data for stacking)
nfolds = 10

# There are a few ways to assemble a list of models to stack together:
# 1. Train individual models and put them in a list
# 2. Train a grid of models
# 3. Train several grids of models
# Note: All base models must have the same cross-validation folds and
# the cross-validated predicted values must be kept.


# 1. Generate a 2-model ensemble (GBM + RF)

# Train and cross-validate a GBM
my_gbm = H2OGradientBoostingEstimator(distribution="bernoulli",
                                      ntrees=100,
                                      max_depth=3,
                                      min_rows=2,
                                      learn_rate=0.001,
                                      nfolds=nfolds,
                                      fold_assignment="Modulo",
                                      keep_cross_validation_predictions=True,
                                      seed=1)
my_gbm.train(x=x, y=y, training_frame=train_raw)


# Train and cross-validate a RF
my_rf = H2ORandomForestEstimator(ntrees=100,
                                 nfolds=nfolds,
                                 fold_assignment="Modulo",
                                 keep_cross_validation_predictions=True,
                                 seed=1)
my_rf.train(x=x, y=y, training_frame=train_raw)


# Train a stacked ensemble using the GBM and GLM above
ensemble = H2OStackedEnsembleEstimator(model_id="ensemble_baseline",
                                       base_models=[my_gbm, my_rf,best_gbm1,aml.leader])
ensemble.train(x=x, y=y, training_frame=train_raw)

gbm Model Build progress: |███████████████████████████████████████████████| 100%
drf Model Build progress: |███████████████████████████████████████████████| 100%
stackedensemble Model Build progress: | (failed)

OSError: Job with key $03017f00000132d4ffffffff$_8bec9baf5a07f85c4eb01f71f85b42fd failed with an exception: java.lang.NullPointerException
stacktrace:
java.lang.NullPointerException
	at hex.StackedEnsembleModel.checkAndInheritModelProperties(StackedEnsembleModel.java:313)
	at hex.ensemble.StackedEnsemble$StackedEnsembleDriver.computeImpl(StackedEnsemble.java:234)
	at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:214)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1267)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

In [281]:
# Train a stacked ensemble using the GBM and GLM above
ensemble = H2OStackedEnsembleEstimator(
                                       base_models=[my_gbm, my_rf])
ensemble.train(x=x, y=y, training_frame=train_raw)

stackedensemble Model Build progress: |███████████████████████████████████| 100%

In [269]:
# Train a stacked ensemble using the GBM and GLM above
ensemble = H2OStackedEnsembleEstimator(base_models=[my_gbm, my_rf,])
ensemble.train(x=x, y=y, training_frame=train_raw)

stackedensemble Model Build progress: |███████████████████████████████████| 100%

In [270]:
pred_stackensemble = ensemble.predict(test_raw).as_data_frame()
pred_stackensemble['employee_id'] = test_raw['employee_id'].as_data_frame()
pred_stackensemble.to_csv("stackensemble_baseline1.csv")

stackedensemble prediction progress: |████████████████████████████████████| 100%

In [264]:
# Train a stacked ensemble using the GBM and GLM above
ensemble = H2OStackedEnsembleEstimator(model_id="my_ensemble_binomial",
                                       base_models=[my_gbm, my_rf])
ensemble.train(x=x, y=y, training_frame=train_raw)

stackedensemble Model Build progress: | (failed)

OSError: Job with key $03017f00000132d4ffffffff$_9662258c68ed53e2fa594fc718784d53 failed with an exception: java.lang.IllegalArgumentException: class hex.StackedEnsembleModel my_ensemble_binomial is already in use.  Unable to use it now.  Consider using a different destination name.
stacktrace:
java.lang.IllegalArgumentException: class hex.StackedEnsembleModel my_ensemble_binomial is already in use.  Unable to use it now.  Consider using a different destination name.
	at water.Lockable$PriorWriteLock.atomic(Lockable.java:113)
	at water.Lockable$PriorWriteLock.atomic(Lockable.java:102)
	at water.TAtomic.atomic(TAtomic.java:17)
	at water.Atomic.compute2(Atomic.java:56)
	at water.Atomic.fork(Atomic.java:39)
	at water.Atomic.invoke(Atomic.java:31)
	at water.Lockable.write_lock(Lockable.java:61)
	at water.Lockable.delete_and_lock(Lockable.java:70)
	at water.Lockable.delete_and_lock(Lockable.java:68)
	at hex.ensemble.StackedEnsemble$StackedEnsembleDriver.computeImpl(StackedEnsemble.java:232)
	at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:214)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1267)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

In [249]:
valid

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,...,age_group_2,age_group_3,avg_traiing_score_1,avg_traiing_score_2,avg_traiing_score_3,avg_traiing_score_4,avg_traiing_score_5,avg_traiing_score_6,avg_traiing_score_7,avg_traiing_score_8
0,49017,Sales & Marketing,region_7,0,f,sourcing,1,35,5,3,...,1,0,0,0,0,0,0,0,0,0
1,71177,Procurement,region_5,0,m,other,1,27,0,1,...,0,0,0,0,0,0,0,0,0,0
2,61758,Analytics,region_2,0,m,other,1,44,5,12,...,0,0,0,1,0,0,0,0,0,0
3,26599,Sales & Marketing,region_16,0,m,other,2,27,0,1,...,0,0,0,0,0,0,0,0,0,0
4,9150,Analytics,region_22,0,f,other,1,28,0,1,...,0,0,1,0,0,0,0,0,0,0
5,77577,Sales & Marketing,region_7,0,m,other,1,50,3,14,...,0,0,0,0,0,0,0,0,0,0
6,44575,Legal,region_7,0,m,other,1,29,0,1,...,0,0,0,0,0,0,0,0,0,0
7,16027,Operations,region_26,0,f,other,1,37,3,11,...,0,0,0,0,0,0,0,0,0,0
8,51444,HR,region_13,0,f,other,1,30,0,1,...,0,0,0,0,0,0,0,0,0,0
9,42068,Operations,region_1,2,m,other,1,38,5,9,...,0,1,0,0,0,0,0,0,0,0
10,51164,Technology,region_14,0,f,other,1,31,4,4,...,0,0,0,0,0,0,0,0,0,0
11,5515,Operations,region_13,2,m,other,1,43,3,7,...,0,0,0,0,0,0,0,0,0,0
12,53373,Operations,region_13,0,m,other,1,36,1,5,...,0,0,0,0,0,0,0,0,0,0
13,74349,Sales & Marketing,region_5,0,m,sourcing,1,34,1,4,...,1,0,0,0,0,0,0,0,0,0
14,62293,Operations,region_27,0,m,other,1,35,4,3,...,1,0,0,0,0,0,0,0,0,0
15,75610,Analytics,region_32,0,m,other,1,29,1,3,...,0,0,1,0,0,0,0,0,0,0
16,57228,HR,region_2,2,m,sourcing,1,44,5,6,...,0,0,0,0,0,0,0,0,0,0
17,27188,Analytics,region_13,2,m,other,1,30,3,4,...,0,0,1,0,0,0,0,0,0,0
18,22300,HR,region_20,0,m,other,1,28,0,1,...,0,0,0,0,0,0,0,0,0,0
19,76080,Operations,region_7,0,f,other,1,34,1,5,...,1,0,0,0,0,0,0,0,0,0
20,59608,Sales & Marketing,region_2,2,f,other,1,41,4,5,...,0,0,0,0,0,0,0,0,0,0
21,34312,Procurement,region_2,2,f,other,2,54,4,23,...,0,0,0,0,0,0,0,0,0,0
22,27989,Analytics,region_34,0,m,sourcing,1,32,3,7,...,0,0,1,0,0,0,0,0,0,0
23,12598,Analytics,region_6,0,m,sourcing,1,29,4,4,...,0,0,0,0,0,0,0,0,0,0
24,58415,Sales & Marketing,region_7,0,m,other,1,45,4,5,...,0,0,0,0,0,0,0,0,0,0
25,26107,Sales & Marketing,region_26,0,m,other,1,30,1,7,...,0,0,0,0,0,0,0,0,0,0
26,8284,Sales & Marketing,region_2,0,f,other,1,34,5,5,...,1,0,0,0,0,0,0,0,0,0
27,36936,Sales & Marketing,region_28,-1,m,other,1,24,2,2,...,0,0,0,0,0,0,0,0,0,0
28,34965,Operations,region_26,0,m,other,2,31,3,4,...,0,0,0,0,0,0,0,0,0,0
29,70048,Sales & Marketing,region_1,2,m,other,1,37,3,10,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,6356,Procurement,region_2,0,f,other,1,48,3,13,...,0,0,0,0,0,0,0,0,0,0
4410,31276,Technology,region_2,0,m,referred,1,38,3,5,...,0,1,0,0,0,0,0,0,0,0
4411,10882,Sales & Marketing,region_25,2,m,sourcing,2,32,4,5,...,0,0,0,0,0,0,0,1,0,0
4412,27846,Operations,region_15,2,m,sourcing,1,41,4,6,...,0,0,0,0,0,0,0,0,0,0
4413,46631,Technology,region_9,0,m,sourcing,1,28,3,3,...,0,0,1,0,0,0,0,0,0,0
4414,34728,Technology,region_26,2,f,sourcing,1,40,1,5,...,0,0,0,0,0,0,0,0,0,0
4415,51548,Finance,region_26,0,m,sourcing,1,29,3,2,...,0,0,0,0,0,0,0,0,0,0
4416,26441,Technology,region_31,0,m,other,1,37,4,4,...,0,0,0,0,0,0,0,0,0,0
4417,27057,Technology,region_2,2,m,other,1,43,3,12,...,0,0,1,0,0,0,0,0,0,0
4418,4072,Operations,region_2,-1,m,sourcing,1,40,3,12,...,0,0,0,0,0,0,0,0,0,0
4419,29434,Technology,region_2,-1,m,other,1,33,5,10,...,1,0,1,0,0,0,0,0,0,0
4420,19453,Technology,region_2,0,m,other,2,31,3,3,...,0,0,0,0,0,0,0,0,0,0
4421,67583,HR,region_2,0,m,referred,1,26,5,2,...,0,0,0,0,0,0,0,0,0,0
4422,16455,Sales & Marketing,region_15,0,m,other,2,31,3,2,...,0,0,0,0,0,0,0,0,0,0
4423,33515,Operations,region_2,0,f,other,1,38,1,4,...,0,1,0,0,0,0,0,0,0,0
4424,5072,Operations,region_26,2,m,other,1,33,5,3,...,1,0,0,0,0,0,0,0,0,0
4425,45494,Sales & Marketing,region_19,0,m,other,1,29,0,1,...,0,0,0,0,0,0,0,0,0,0
4426,12914,Operations,region_2,0,f,other,1,40,3,11,...,0,0,0,0,0,0,1,0,0,0
4427,67677,Procurement,region_16,0,m,sourcing,6,30,3,5,...,0,0,0,0,0,0,0,0,0,0
4428,7629,Technology,region_27,0,m,other,2,31,3,4,...,0,0,1,0,0,0,0,0,0,0
4429,64521,Technology,region_2,0,f,sourcing,2,25,0,1,...,0,0,0,0,0,0,0,0,0,0
4430,63615,Sales & Marketing,region_27,0,f,other,1,31,3,4,...,0,0,0,0,0,0,0,0,0,0
4431,67212,Procurement,region_2,2,f,other,1,35,4,6,...,1,0,0,0,0,0,0,0,0,0
4432,70103,Analytics,region_22,0,m,sourcing,1,34,2,7,...,1,0,1,0,0,0,0,0,0,0
4433,11685,Operations,region_15,0,m,sourcing,1,31,0,1,...,0,0,0,0,0,0,0,0,0,0
4434,60634,Procurement,region_15,0,m,other,1,31,3,7,...,0,0,0,0,0,0,0,0,0,0
4435,398,Sales & Marketing,region_19,0,f,sourcing,1,34,3,9,...,1,0,0,0,0,0,0,0,0,0
4436,57287,Operations,region_26,0,m,other,1,30,1,2,...,0,0,0,0,0,0,0,0,0,0
4437,67988,HR,region_2,0,f,sourcing,1,48,5,4,...,0,0,0,0,0,0,0,0,0,0
4438,62450,Sales & Marketing,region_11,0,m,sourcing,1,28,5,3,...,0,0,0,0,0,0,0,0,0,0

In [244]:
def xgb_eval_mae(yhat, dtrain):
    y = dtrain.get_label()
    return 'mae', mean_absolute_error(np.exp(y), np.exp(yhat))

def objective(space):

    clf = xgb.XGBRegressor(n_estimators = space['n_estimators'],
                           max_depth = space['max_depth'],
                           min_child_weight = space['min_child_weight'],
                           subsample = space['subsample'],
                           learning_rate = space['learning_rate'],
                           gamma = space['gamma'],
                           colsample_bytree = space['colsample_bytree'],
                           objective='reg:linear',
                           early_stopping_rounds = 10
                           )

    eval_set  = [( train, y_train), ( valid, y_valid)]

    clf.fit(train[col_train],
            y_train,
            eval_set=eval_set,
            eval_metric = 'mae')
    pred = clf.predict(valid)
    #   mae = mean_absolute_error(np.exp(y_valid), np.exp(pred))
    mae = mean_absolute_error((y_valid), (pred))

    #    print "SCORE:", mae
    return{'loss':mae, 'status': STATUS_OK }


space = {
        'max_depth': hp.choice('max_depth', np.arange(10, 30, dtype=int)),
        'min_child_weight': hp.quniform ('min_child', 1, 20, 1),
        'subsample': hp.uniform ('subsample', 0.8, 1),
        'n_estimators' : hp.choice('n_estimators', np.arange(1000, 10000, 100, dtype=int)),
        'learning_rate' : hp.quniform('learning_rate', 0.025, 0.5, 0.025),
        'gamma' : hp.quniform('gamma', 0.5, 1, 0.05),
        'colsample_bytree' : hp.quniform('colsample_bytree', 0.5, 1, 0.05)
    }

In [245]:
train = train.as_data_frame()
valid = valid.as_data_frame()


features = train.columns

cats = [feat for feat in features if 'cat' in feat]
for feat in cats:
    train[feat] = pd.factorize(train[feat], sort=True)[0]
    valid[feat] = pd.factorize(valid[feat], sort=True)[0]


y_train = (train[y])
y_valid = (valid[y])

In [247]:
del train['']
del valid[y]

KeyError: 'is_promoted'

In [246]:

#y_train = np.log(train[target].ravel())
#y_valid = np.log(valid[target].ravel())


col_train = train.columns

trials = Trials()

best = fmin(fn=objective,
            space=space,
            algo=tpe.suggest,
            max_evals = 100, # change
            trials=trials)

ValueError: DataFrame.dtypes for data must be int, float or bool.
                Did not expect the data types in fields department, region, gender, recruitment_channel

In [274]:
valid

NameError: name 'dim' is not defined

In [256]:
test_raw.as_data_frame().to_csv('test_mod.csv')

In [283]:
param = {
      "ntrees" : 1000
    , "max_depth" : 10
    , "learn_rate" : 0.001
    , "sample_rate" : 0.7
    , "col_sample_rate_per_tree" : 0.9
    , "min_rows" : 5
    , "seed": 4241
    , "score_tree_interval": 100
}

from h2o.estimators import H2OXGBoostEstimator
model = H2OXGBoostEstimator(**param)

In [284]:
model.train(x = list(range(1, train_raw.shape[1])), y = 'is_promoted', training_frame = train_raw, validation_frame = train_raw)

xgboost Model Build progress: |███████████████████████████████████████████| 100%

In [285]:
pred_xgb = model.predict(test_raw).as_data_frame()
pred_xgb['employee_id'] = test_raw['employee_id'].as_data_frame()
pred_xgb.to_csv("pred_xgb2.csv")

xgboost prediction progress: |████████████████████████████████████████████| 100%

In [286]:
target = 'is_promoted'
ID = 'employee_id'
# train_raw.drop([ID], axis=1)
train, valid = train_raw.split_frame(ratios=[0.9], seed=1)
# valid = data.drop(train.index)
features = train.columns

x = train.columns
y = "is_promoted"
x.remove(y)

ID = 'employee_id'
x.remove(ID)

In [305]:
h2o.init(max_mem_size="12G")

Checking whether there is an H2O instance running at http://localhost:54321. connected.

--------------------------  ----------------------------------------
H2O cluster uptime:         1 day 9 hours 32 mins
H2O cluster timezone:       Asia/Kolkata
H2O data parsing timezone:  UTC
H2O cluster version:        3.20.0.7
H2O cluster version age:    15 days
H2O cluster name:           H2O_from_python_reetkanjilal_nhmelh
H2O cluster total nodes:    1
H2O cluster free memory:    0
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             3.5.2 final
--------------------------  ----------------------------------------

In [299]:
# GBM hyperparameters
x = train.columns
y = "is_promoted"
x.remove(y)
ID = 'employee_id'
x.remove(ID)





param = {
      "ntrees" : 10
    , "min_rows" : 5
    , "seed": 4241
    , "score_tree_interval": 1
}



gbm_params1 = {'learn_rate': [0.01, 0.1],
                'max_depth': [3, 5],
                'sample_rate': [0.8, 1.0],
                'col_sample_rate': [0.8,1.0]}

# Train and validate a cartesian grid of GBMs
xgb_grid1 = H2OGridSearch(H2OXGBoostEstimator(**param),
                          grid_id='xgb_grid1',
                          hyper_params=gbm_params1)

xgb_grid1.train(x=x, y=y, training_frame=train,validation_frame=valid,ntrees=5)

# xgb_grid1.train(x=x, y=0,
#                 training_frame=train,
#                 validation_frame=valid,
#                 ntrees=5, 
#                 seed=1)

xgboost Grid Build progress: |███████ (failed)

OSError: Job with key $03017f00000132d4ffffffff$_aa7fec97983b1a8f792fd89840e94f2b failed with an exception: java.lang.AssertionError: I am really confused about the heap usage; MEM_MAX=1908932608 heapUsedGC=1916502664
stacktrace:
java.lang.AssertionError: I am really confused about the heap usage; MEM_MAX=1908932608 heapUsedGC=1916502664
	at water.MemoryManager.set_goals(MemoryManager.java:97)
	at water.MemoryManager.malloc(MemoryManager.java:266)
	at water.MemoryManager.malloc(MemoryManager.java:222)
	at water.MemoryManager.arrayCopyOfRange(MemoryManager.java:292)
	at water.AutoBuffer.buf(AutoBuffer.java:544)
	at water.Iced.asBytes(Iced.java:42)
	at water.Value.<init>(Value.java:354)
	at water.TAtomic.atomic(TAtomic.java:22)
	at water.Atomic.compute2(Atomic.java:56)
	at water.Atomic.fork(Atomic.java:39)
	at water.Atomic.invoke(Atomic.java:31)
	at water.Lockable.update(Lockable.java:157)
	at water.Lockable.update(Lockable.java:154)
	at hex.grid.GridSearch.gridSearch(GridSearch.java:240)
	at hex.grid.GridSearch.access$000(GridSearch.java:69)
	at hex.grid.GridSearch$1.compute2(GridSearch.java:136)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1267)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

In [306]:
h2o.cluster_status()

[WARNING] in <ipython-input-306-d20854194a71> line 1:
    >>> h2o.cluster_status()
        ^^^^ Deprecated, use ``h2o.cluster().show_status(True)``.

--------------------------  ----------------------------------------
H2O cluster uptime:         1 day 9 hours 32 mins
H2O cluster timezone:       Asia/Kolkata
H2O data parsing timezone:  UTC
H2O cluster version:        3.20.0.7
H2O cluster version age:    15 days
H2O cluster name:           H2O_from_python_reetkanjilal_nhmelh
H2O cluster total nodes:    1
H2O cluster free memory:    0
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             3.5.2 final
--------------------------  ----------------------------------------

Nodes info:     Node 1
--------------  ----------------
h2o             /127.0.0.1:54321
healthy         True
last_ping       1537083206727
num_cpus        4
sys_load        2.1679688
mem_value_size  1813931938
free_mem        0
pojo_mem        95000670
swap_mem        0
free_disk       31397511168
max_disk        121122062336
pid             19527
num_keys        84899
tcps_active     0
open_fds        -1
rpcs_active     0

In [307]:
h2o.cluster().shutdown()